<?xml version="1.0" encoding="utf-8"?>
<clsResultsOfOneSearch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <CfgVersion>0.001</CfgVersion>
    <SearchProperties>
        <CfgVersion>0.001</CfgVersion>
        <bUseFileRegularExpression>false</bUseFileRegularExpression>
        <bSearchInsideZipFiles>false</bSearchInsideZipFiles>
        <bSkipFileTypes>false</bSkipFileTypes>
        <SkipFileTypesString />
        <bUseFolderRegularExpression>false</bUseFolderRegularExpression>
        <bDoRecourseFolders>true</bDoRecourseFolders>
        <ViewSetting>
            <Show>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Show>
            <Keep>
                <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
            </Keep>
            <bDoShowTitle>true</bDoShowTitle>
            <bDoShowLineNumbers>true</bDoShowLineNumbers>
            <bDoShowFixedFont>true</bDoShowFixedFont>
            <bDoShowFileNames>false</bDoShowFileNames>
            <bDoShowFileContents>true</bDoShowFileContents>
            <bDoShowWholeLine>true</bDoShowWholeLine>
            <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
        </ViewSetting>
        <ShowViewSelection>
            <Show>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Show>
            <Keep>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Keep>
            <bDoShowTitle>true</bDoShowTitle>
            <bDoShowLineNumbers>true</bDoShowLineNumbers>
            <bDoShowFixedFont>true</bDoShowFixedFont>
            <bDoShowFileNames>true</bDoShowFileNames>
            <bDoShowFileContents>true</bDoShowFileContents>
            <bDoShowWholeLine>true</bDoShowWholeLine>
            <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
        </ShowViewSelection>
        <SearchString>Joomla.check</SearchString>
        <ReplaceString>-&gt;loadColumn</ReplaceString>
        <SearchFileTypes>
            <string>*.php</string>
            <string>*.js</string>
        </SearchFileTypes>
        <SearchFileTypesAsString>*.php *.js</SearchFileTypesAsString>
        <SearchFolders>
            <string>d:\xampp\htdocs\Joomla3x\</string>
        </SearchFolders>
        <SearchFoldersAsString>d:\xampp\htdocs\Joomla3x\</SearchFoldersAsString>
        <bWholeWordsOnly>false</bWholeWordsOnly>
        <bMatchCase>false</bMatchCase>
        <bLinesWithNoMatch>false</bLinesWithNoMatch>
        <bStopAfterFirstMatch>false</bStopAfterFirstMatch>
        <bUseRegularExpression>false</bUseRegularExpression>
        <bFilesWithNoMatch>false</bFilesWithNoMatch>
        <bSearchInFoundFiles>false</bSearchInFoundFiles>
        <bUseDelimitedList>false</bUseDelimitedList>
        <bUseFixedWidthList>false</bUseFixedWidthList>
        <bNeedsCompleteLine>false</bNeedsCompleteLine>
        <DelimitedSeperationChar />
        <DelimitedSearchFieldNbr />
        <FixedWidthBeginPosition />
        <FixedWidthSize />
        <bReplaceInSelectedFiles>false</bReplaceInSelectedFiles>
        <bConfirmEachReplace>false</bConfirmEachReplace>
        <bCreateBackup>false</bCreateBackup>
        <bReplaceOriginalFile>true</bReplaceOriginalFile>
        <bUseBackupFolder>false</bUseBackupFolder>
        <BackupFolder>Use backup folder</BackupFolder>
    </SearchProperties>
    <SearchResults>
        <Files2LineResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_contenthistory\views\history\tmpl\modal.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>115</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\views\galleries\tmpl\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>						&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>54</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>123</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\views\Images\tmpl\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>						&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>54</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>123</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsgallery2\views\maintConsolidateDB\tmpl\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>	echo '            &lt;th&gt;' . '&lt;input class="hasTooltip" type="checkbox" onclick="Joomla.checkAll(this)" title="" value="" </Line>
                        <LineIdx>51</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>79</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_banners\banners\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>84</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_banners\clients\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>59</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_cache\cache\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>				&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>44</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>121</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_categories\categories\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>							&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>88</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>124</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_checkin\checkin\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>						&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>36</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>123</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_contact\contacts\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>94</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_content\articles\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>97</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_content\featured\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>84</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_finder\filters\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>73</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_finder\index\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>92</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_finder\maps\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>80</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_installer\discover\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>				&lt;th class="checkmark-col"&gt;&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;&lt;/th&gt;</Line>
                        <LineIdx>41</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>147</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_installer\languages\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>							&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>39</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>124</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_installer\manage\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>44</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_installer\update\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>				&lt;th class="checkmark-col"&gt;&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;&lt;/th&gt;</Line>
                        <LineIdx>41</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>147</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_languages\languages\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>62</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_languages\overrides\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>49</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>69</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_menus\items\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>96</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_menus\menus\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>69</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_messages\messages\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>59</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_modules\modules\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>103</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_newsfeeds\newsfeeds\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>96</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_plugins\plugins\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>75</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_redirect\links\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>59</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_tags\tags\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>77</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_users\groups\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>76</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_users\levels\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>48</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_users\notes\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="toggle" value="" class="checklist-toggle" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>71</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>138</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_users\users\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>86</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\templates\hathor\html\com_weblinks\weblinks\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>					&lt;input type="checkbox" name="checkall-toggle" value="" title="&lt;?php echo JText::_('JGLOBAL_CHECK_ALL'); ?&gt;" onclick="Joomla.checkAll(this)" /&gt;</Line>
                        <LineIdx>94</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>122</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\libraries\cms\html\grid.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>	public static function checkall($name = 'checkall-toggle', $tip = 'JGLOBAL_CHECK_ALL', $action = 'Joomla.checkAll(this)')</Line>
                        <LineIdx>123</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>99</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\libraries\fof\form\header\rowselect.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			. '" onclick="Joomla.checkAll(this)" /&gt;';</Line>
                        <LineIdx>28</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>17</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\media\system\js\core-uncompressed.js</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>	Joomla.checkAll = function( checkbox, stub ) {</Line>
                        <LineIdx>116</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>1</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
        </Files2LineResults>
        <SearchResultInfo>
            <SearchProperties>
                <CfgVersion>0.001</CfgVersion>
                <bUseFileRegularExpression>false</bUseFileRegularExpression>
                <bSearchInsideZipFiles>false</bSearchInsideZipFiles>
                <bSkipFileTypes>false</bSkipFileTypes>
                <SkipFileTypesString />
                <bUseFolderRegularExpression>false</bUseFolderRegularExpression>
                <bDoRecourseFolders>true</bDoRecourseFolders>
                <ViewSetting>
                    <Show>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Show>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                    <bDoShowTitle>true</bDoShowTitle>
                    <bDoShowLineNumbers>true</bDoShowLineNumbers>
                    <bDoShowFixedFont>true</bDoShowFixedFont>
                    <bDoShowFileNames>false</bDoShowFileNames>
                    <bDoShowFileContents>true</bDoShowFileContents>
                    <bDoShowWholeLine>true</bDoShowWholeLine>
                    <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
                </ViewSetting>
                <ShowViewSelection>
                    <Show>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Show>
                    <Keep>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Keep>
                    <bDoShowTitle>true</bDoShowTitle>
                    <bDoShowLineNumbers>true</bDoShowLineNumbers>
                    <bDoShowFixedFont>true</bDoShowFixedFont>
                    <bDoShowFileNames>true</bDoShowFileNames>
                    <bDoShowFileContents>true</bDoShowFileContents>
                    <bDoShowWholeLine>true</bDoShowWholeLine>
                    <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
                </ShowViewSelection>
                <SearchString>Joomla.check</SearchString>
                <ReplaceString>-&gt;loadColumn</ReplaceString>
                <SearchFileTypes>
                    <string>*.php</string>
                    <string>*.js</string>
                </SearchFileTypes>
                <SearchFileTypesAsString>*.php *.js</SearchFileTypesAsString>
                <SearchFolders>
                    <string>d:\xampp\htdocs\Joomla3x\</string>
                </SearchFolders>
                <SearchFoldersAsString>d:\xampp\htdocs\Joomla3x\</SearchFoldersAsString>
                <bWholeWordsOnly>false</bWholeWordsOnly>
                <bMatchCase>false</bMatchCase>
                <bLinesWithNoMatch>false</bLinesWithNoMatch>
                <bStopAfterFirstMatch>false</bStopAfterFirstMatch>
                <bUseRegularExpression>false</bUseRegularExpression>
                <bFilesWithNoMatch>false</bFilesWithNoMatch>
                <bSearchInFoundFiles>false</bSearchInFoundFiles>
                <bUseDelimitedList>false</bUseDelimitedList>
                <bUseFixedWidthList>false</bUseFixedWidthList>
                <bNeedsCompleteLine>false</bNeedsCompleteLine>
                <DelimitedSeperationChar />
                <DelimitedSearchFieldNbr />
                <FixedWidthBeginPosition />
                <FixedWidthSize />
                <bReplaceInSelectedFiles>false</bReplaceInSelectedFiles>
                <bConfirmEachReplace>false</bConfirmEachReplace>
                <bCreateBackup>false</bCreateBackup>
                <bReplaceOriginalFile>true</bReplaceOriginalFile>
                <bUseBackupFolder>false</bUseBackupFolder>
                <BackupFolder>Use backup folder</BackupFolder>
            </SearchProperties>
            <TokenMatchedNbr>37</TokenMatchedNbr>
            <FilesMatchedNbr>37</FilesMatchedNbr>
            <FileSearchedNbr>4402</FileSearchedNbr>
            <FilesSkippedNbr>0</FilesSkippedNbr>
        </SearchResultInfo>
    </SearchResults>
</clsResultsOfOneSearch>