<?xml version="1.0" encoding="utf-8"?>
<clsResultsOfOneSearch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <CfgVersion>0.001</CfgVersion>
    <SearchProperties>
        <CfgVersion>0.001</CfgVersion>
        <bUseFileRegularExpression>false</bUseFileRegularExpression>
        <bSearchInsideZipFiles>false</bSearchInsideZipFiles>
        <bSkipFileTypes>false</bSkipFileTypes>
        <SkipFileTypesString />
        <bUseFolderRegularExpression>false</bUseFolderRegularExpression>
        <bDoRecourseFolders>true</bDoRecourseFolders>
        <ViewSetting>
            <Show>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Show>
            <Keep>
                <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
            </Keep>
            <bDoShowTitle>true</bDoShowTitle>
            <bDoShowLineNumbers>true</bDoShowLineNumbers>
            <bDoShowFixedFont>true</bDoShowFixedFont>
            <bDoShowFileNames>true</bDoShowFileNames>
            <bDoShowFileContents>true</bDoShowFileContents>
            <bDoShowWholeLine>true</bDoShowWholeLine>
            <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
        </ViewSetting>
        <ShowViewSelection>
            <Show>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Show>
            <Keep>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Keep>
            <bDoShowTitle>true</bDoShowTitle>
            <bDoShowLineNumbers>true</bDoShowLineNumbers>
            <bDoShowFixedFont>true</bDoShowFixedFont>
            <bDoShowFileNames>true</bDoShowFileNames>
            <bDoShowFileContents>true</bDoShowFileContents>
            <bDoShowWholeLine>true</bDoShowWholeLine>
            <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
        </ShowViewSelection>
        <SearchString>listItemTask</SearchString>
        <ReplaceString>-&gt;loadColumn</ReplaceString>
        <SearchFileTypes>
            <string>*.php</string>
        </SearchFileTypes>
        <SearchFileTypesAsString>*.php</SearchFileTypesAsString>
        <SearchFolders>
            <string>d:\xampp\htdocs\Joomla3x\</string>
        </SearchFolders>
        <SearchFoldersAsString>d:\xampp\htdocs\Joomla3x\</SearchFoldersAsString>
        <bWholeWordsOnly>false</bWholeWordsOnly>
        <bMatchCase>false</bMatchCase>
        <bLinesWithNoMatch>false</bLinesWithNoMatch>
        <bStopAfterFirstMatch>false</bStopAfterFirstMatch>
        <bUseRegularExpression>false</bUseRegularExpression>
        <bFilesWithNoMatch>false</bFilesWithNoMatch>
        <bSearchInFoundFiles>false</bSearchInFoundFiles>
        <bUseDelimitedList>false</bUseDelimitedList>
        <bUseFixedWidthList>false</bUseFixedWidthList>
        <bNeedsCompleteLine>false</bNeedsCompleteLine>
        <DelimitedSeperationChar />
        <DelimitedSearchFieldNbr />
        <FixedWidthBeginPosition />
        <FixedWidthSize />
        <bReplaceInSelectedFiles>false</bReplaceInSelectedFiles>
        <bConfirmEachReplace>false</bConfirmEachReplace>
        <bCreateBackup>false</bCreateBackup>
        <bReplaceOriginalFile>true</bReplaceOriginalFile>
        <bUseBackupFolder>false</bUseBackupFolder>
        <BackupFolder>Use backup folder</BackupFolder>
    </SearchProperties>
    <SearchResults>
        <Files2LineResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_componentarchitect\codetemplates\j_3_3_standard\com_architectcomp_j33standard\admin\helpers\html\compobjectadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>155</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_componentarchitect\codetemplates\j_3_4_standard\com_architectcomp_j34standard\admin\helpers\html\compobjectadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>155</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_contact\helpers\html\contact.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html = '&lt;a href="#" onclick="return listItemTask(\'cb' . $i . '\',\'' . $state[1] . '\')" class="btn btn-micro hasTooltip'</Line>
                        <LineIdx>129</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_content\helpers\html\contentadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html = '&lt;a href="#" onclick="return listItemTask(\'cb' . $i . '\',\'' . $state[1] . '\')" class="btn btn-micro hasTooltip'</Line>
                        <LineIdx>122</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_contenthistory\views\history\tmpl\modal.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>							onclick="return listItemTask('cb&lt;?php echo $i; ?&gt;','history.keep')"</Line>
                        <LineIdx>163</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>23</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>							onclick="return listItemTask('cb&lt;?php echo $i; ?&gt;','history.keep')"</Line>
                        <LineIdx>169</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>23</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_messages\helpers\html\messages.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html = '&lt;a href="#" onclick="return listItemTask(\'cb' . $i . '\',\'' . $state[1] . '\')" class="btn btn-micro hasTooltip'</Line>
                        <LineIdx>81</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_redirect\helpers\html\redirect.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html = '&lt;a href="#" onclick="return listItemTask(\'cb' . $i . '\',\'' . $state[1] . '\')" class="btn btn-micro hasTooltip'</Line>
                        <LineIdx>53</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsgallery2\views\maintConsolidateDB\tmpl\default.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html[] = '         onclick="return listItemTask(\'cb&lt;?php echo $i;?&gt;\', 'categories . \')"\';';</Line>
                        <LineIdx>96</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>39</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>			echo '			onclick="return listItemTask(\'cb1\',\'categories.unpublish\')"';</Line>
                        <LineIdx>118</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>28</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>			 * $html[] = ' href="javascript:void(0);" onclick="return listItemTask(\'' . $checkbox . $i . '\',\'' . $prefix . $task . '\')"';</Line>
                        <LineIdx>126</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>61</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>			 * $html[] = '&lt;a href="#" onclick="return listItemTask(\'cb' . $i . '\',\'' . $state[1] . '\')" class="btn btn-micro hasTooltip'</Line>
                        <LineIdx>142</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>45</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>//	&lt;a class="btn btn-micro active hasTooltip" href="javascript:void(0);" onclick="return listItemTask('cb0','categories.unpublish')" title="Unpublish Item"&gt;&lt;span class="icon-publish"&gt;&lt;/span&gt;&lt;/a&gt;</Line>
                        <LineIdx>210</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>89</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_testgallery01\helpers\html\acladministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>125</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_testgallery01\helpers\html\commentsadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>125</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_testgallery01\helpers\html\configadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>128</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_testgallery01\helpers\html\galleryadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>125</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_testgallery01\helpers\html\imagesadministrator.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html	= '&lt;a href="#" onclick="return listItemTask(\'cb'.$i.'\',\''.$state[1].'\')" class="btn btn-micro hasTooltip' . ($value == 1 ? ' active' : '') . '" title="'.JText::_($state[3]).'"&gt;&lt;i class="icon-'</Line>
                        <LineIdx>125</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>40</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\libraries\cms\html\actionsdropdown.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			. '&lt;a href = "javascript://" onclick="listItemTask(\'' . $id . '\', \'' . $task . '\')"&gt;'</Line>
                        <LineIdx>226</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>41</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\libraries\cms\html\grid.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>		return '&lt;a href="#" onclick="return listItemTask(\'cb' . $i . '\',\'' . $prefix . $task . '\')" title="' . $action . '"&gt;'</Line>
                        <LineIdx>217</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>38</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>					listItemTask(args.id, args.task);</Line>
                        <LineIdx>330</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>5</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\libraries\cms\html\jgrid.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			$html[] = ' href="javascript:void(0);" onclick="return listItemTask(\'' . $checkbox . $i . '\',\'' . $prefix . $task . '\')"';</Line>
                        <LineIdx>68</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>58</StartIdx>
                                <Length>12</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
        </Files2LineResults>
        <SearchResultInfo>
            <SearchProperties>
                <CfgVersion>0.001</CfgVersion>
                <bUseFileRegularExpression>false</bUseFileRegularExpression>
                <bSearchInsideZipFiles>false</bSearchInsideZipFiles>
                <bSkipFileTypes>false</bSkipFileTypes>
                <SkipFileTypesString />
                <bUseFolderRegularExpression>false</bUseFolderRegularExpression>
                <bDoRecourseFolders>true</bDoRecourseFolders>
                <ViewSetting>
                    <Show>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Show>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                    <bDoShowTitle>true</bDoShowTitle>
                    <bDoShowLineNumbers>true</bDoShowLineNumbers>
                    <bDoShowFixedFont>true</bDoShowFixedFont>
                    <bDoShowFileNames>true</bDoShowFileNames>
                    <bDoShowFileContents>true</bDoShowFileContents>
                    <bDoShowWholeLine>true</bDoShowWholeLine>
                    <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
                </ViewSetting>
                <ShowViewSelection>
                    <Show>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Show>
                    <Keep>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Keep>
                    <bDoShowTitle>true</bDoShowTitle>
                    <bDoShowLineNumbers>true</bDoShowLineNumbers>
                    <bDoShowFixedFont>true</bDoShowFixedFont>
                    <bDoShowFileNames>true</bDoShowFileNames>
                    <bDoShowFileContents>true</bDoShowFileContents>
                    <bDoShowWholeLine>true</bDoShowWholeLine>
                    <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
                </ShowViewSelection>
                <SearchString>listItemTask</SearchString>
                <ReplaceString>-&gt;loadColumn</ReplaceString>
                <SearchFileTypes>
                    <string>*.php</string>
                </SearchFileTypes>
                <SearchFileTypesAsString>*.php</SearchFileTypesAsString>
                <SearchFolders>
                    <string>d:\xampp\htdocs\Joomla3x\</string>
                </SearchFolders>
                <SearchFoldersAsString>d:\xampp\htdocs\Joomla3x\</SearchFoldersAsString>
                <bWholeWordsOnly>false</bWholeWordsOnly>
                <bMatchCase>false</bMatchCase>
                <bLinesWithNoMatch>false</bLinesWithNoMatch>
                <bStopAfterFirstMatch>false</bStopAfterFirstMatch>
                <bUseRegularExpression>false</bUseRegularExpression>
                <bFilesWithNoMatch>false</bFilesWithNoMatch>
                <bSearchInFoundFiles>false</bSearchInFoundFiles>
                <bUseDelimitedList>false</bUseDelimitedList>
                <bUseFixedWidthList>false</bUseFixedWidthList>
                <bNeedsCompleteLine>false</bNeedsCompleteLine>
                <DelimitedSeperationChar />
                <DelimitedSearchFieldNbr />
                <FixedWidthBeginPosition />
                <FixedWidthSize />
                <bReplaceInSelectedFiles>false</bReplaceInSelectedFiles>
                <bConfirmEachReplace>false</bConfirmEachReplace>
                <bCreateBackup>false</bCreateBackup>
                <bReplaceOriginalFile>true</bReplaceOriginalFile>
                <bUseBackupFolder>false</bUseBackupFolder>
                <BackupFolder>Use backup folder</BackupFolder>
            </SearchProperties>
            <TokenMatchedNbr>22</TokenMatchedNbr>
            <FilesMatchedNbr>16</FilesMatchedNbr>
            <FileSearchedNbr>3641</FileSearchedNbr>
            <FilesSkippedNbr>0</FilesSkippedNbr>
        </SearchResultInfo>
    </SearchResults>
</clsResultsOfOneSearch>