<?xml version="1.0" encoding="utf-8"?>
<clsResultsOfOneSearch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <CfgVersion>0.001</CfgVersion>
    <SearchProperties>
        <CfgVersion>0.001</CfgVersion>
        <bUseFileRegularExpression>false</bUseFileRegularExpression>
        <bSearchInsideZipFiles>false</bSearchInsideZipFiles>
        <bSkipFileTypes>false</bSkipFileTypes>
        <SkipFileTypesString />
        <bUseFolderRegularExpression>false</bUseFolderRegularExpression>
        <bDoRecourseFolders>true</bDoRecourseFolders>
        <ViewSetting>
            <Show>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Show>
            <Keep>
                <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
            </Keep>
            <bDoShowTitle>true</bDoShowTitle>
            <bDoShowLineNumbers>true</bDoShowLineNumbers>
            <bDoShowFixedFont>true</bDoShowFixedFont>
            <bDoShowFileNames>true</bDoShowFileNames>
            <bDoShowFileContents>true</bDoShowFileContents>
            <bDoShowWholeLine>true</bDoShowWholeLine>
            <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
        </ViewSetting>
        <ShowViewSelection>
            <Show>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Show>
            <Keep>
                <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
            </Keep>
            <bDoShowTitle>true</bDoShowTitle>
            <bDoShowLineNumbers>true</bDoShowLineNumbers>
            <bDoShowFixedFont>true</bDoShowFixedFont>
            <bDoShowFileNames>true</bDoShowFileNames>
            <bDoShowFileContents>true</bDoShowFileContents>
            <bDoShowWholeLine>true</bDoShowWholeLine>
            <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
        </ShowViewSelection>
        <SearchString>-&gt;select</SearchString>
        <ReplaceString>-&gt;loadColumn</ReplaceString>
        <SearchFileTypes>
            <string>*.php</string>
        </SearchFileTypes>
        <SearchFileTypesAsString>*.php</SearchFileTypesAsString>
        <SearchFolders>
            <string>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2</string>
        </SearchFolders>
        <SearchFoldersAsString>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2</SearchFoldersAsString>
        <bWholeWordsOnly>false</bWholeWordsOnly>
        <bMatchCase>false</bMatchCase>
        <bLinesWithNoMatch>false</bLinesWithNoMatch>
        <bStopAfterFirstMatch>false</bStopAfterFirstMatch>
        <bUseRegularExpression>false</bUseRegularExpression>
        <bFilesWithNoMatch>false</bFilesWithNoMatch>
        <bSearchInFoundFiles>false</bSearchInFoundFiles>
        <bUseDelimitedList>false</bUseDelimitedList>
        <bUseFixedWidthList>false</bUseFixedWidthList>
        <bNeedsCompleteLine>false</bNeedsCompleteLine>
        <DelimitedSeperationChar />
        <DelimitedSearchFieldNbr />
        <FixedWidthBeginPosition />
        <FixedWidthSize />
        <bReplaceInSelectedFiles>false</bReplaceInSelectedFiles>
        <bConfirmEachReplace>false</bConfirmEachReplace>
        <bCreateBackup>false</bCreateBackup>
        <bReplaceOriginalFile>true</bReplaceOriginalFile>
        <bUseBackupFolder>false</bUseBackupFolder>
        <BackupFolder>Use backup folder</BackupFolder>
    </SearchProperties>
    <SearchResults>
        <Files2LineResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\install.rsgallery2.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>            $query-&gt;select($db-&gt;quoteName('extension_id'))</Line>
                        <LineIdx>137</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>18</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>			$query-&gt;select('count(*)');</Line>
                        <LineIdx>150</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>9</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\classes\GalleryTreeClass.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>		$query-&gt;select('*');</Line>
                        <LineIdx>129</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>		$query-&gt;select('*');</Line>
                        <LineIdx>147</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>		$query-&gt;select('*');</Line>
                        <LineIdx>227</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\helpers\rsg2Common.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>            -&gt;select('username')</Line>
                        <LineIdx>21</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>		$query-&gt;select('manifest_cache');</Line>
                        <LineIdx>46</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\configRaw.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>            -&gt;select ('*')</Line>
                        <LineIdx>76</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>			-&gt;select ('name, value')</Line>
                        <LineIdx>81</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\galleries.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>            -&gt;select('*')</Line>
                        <LineIdx>27</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>            -&gt;select('username')</Line>
                        <LineIdx>49</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>            -&gt;select('*')</Line>
                        <LineIdx>77</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>            -&gt;select('*')</Line>
                        <LineIdx>123</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\images.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>            -&gt;select('*')</Line>
                        <LineIdx>28</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>            -&gt;select('name')</Line>
                        <LineIdx>47</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>            -&gt;select('*')</Line>
                        <LineIdx>78</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>            -&gt;select('*')</Line>
                        <LineIdx>120</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>12</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\SummaryTreeView.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>		$query-&gt;select('*')-&gt;from('#__rsgallery2_galleries');</Line>
                        <LineIdx>92</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>		$query-&gt;select('*');		</Line>
                        <LineIdx>104</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>		$query-&gt;select('*');</Line>
                        <LineIdx>119</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\GalleryCombo.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select('id As value, name As text')</Line>
                        <LineIdx>24</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\GalleryList.01.ok.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select('id As value, name As text')</Line>
                        <LineIdx>25</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\GalleryList.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select('id As value, name As text')</Line>
                        <LineIdx>25</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\ParentGalleryList.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select('id As value, name As text')</Line>
                        <LineIdx>27</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\RsgGalleryOrderingList.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select($DbVarName.' As idx, name as text')</Line>
                        <LineIdx>28</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\RsgGalleryThumbList.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select($db-&gt;quoteName('a.id').' As idx, a.name As text')</Line>
                        <LineIdx>28</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\RsgGalleryThumbnails.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select('id As value, name As text')</Line>
                        <LineIdx>27</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\models\fields\RsgImageOrderingList.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>			-&gt;select($DbVarName.' As idx, name As text')</Line>
                        <LineIdx>28</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>3</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\tables\galleries.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>        $query-&gt;select('id');</Line>
                        <LineIdx>137</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>14</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                    <clsLineResult>
                        <Line>        $query-&gt;select('id');</Line>
                        <LineIdx>160</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>14</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
            <clsFileResults>
                <FileName>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2\tables\images.php</FileName>
                <Size>0</Size>
                <SurroundingFileLines>
                    <InState>ePreFound</InState>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                </SurroundingFileLines>
                <LinesResultInfos>
                    <clsLineResult>
                        <Line>		$query-&gt;select('asset_id');</Line>
                        <LineIdx>127</LineIdx>
                        <ResultInfos>
                            <clsResultInfoInLine>
                                <StartIdx>8</StartIdx>
                                <Length>8</Length>
                            </clsResultInfoInLine>
                        </ResultInfos>
                    </clsLineResult>
                </LinesResultInfos>
            </clsFileResults>
        </Files2LineResults>
        <SearchResultInfo>
            <SearchProperties>
                <CfgVersion>0.001</CfgVersion>
                <bUseFileRegularExpression>false</bUseFileRegularExpression>
                <bSearchInsideZipFiles>false</bSearchInsideZipFiles>
                <bSkipFileTypes>false</bSkipFileTypes>
                <SkipFileTypesString />
                <bUseFolderRegularExpression>false</bUseFolderRegularExpression>
                <bDoRecourseFolders>true</bDoRecourseFolders>
                <ViewSetting>
                    <Show>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Show>
                    <Keep>
                        <LineNbrPreviousToMatch>10</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>10</LineNbrFollowingMatch>
                    </Keep>
                    <bDoShowTitle>true</bDoShowTitle>
                    <bDoShowLineNumbers>true</bDoShowLineNumbers>
                    <bDoShowFixedFont>true</bDoShowFixedFont>
                    <bDoShowFileNames>true</bDoShowFileNames>
                    <bDoShowFileContents>true</bDoShowFileContents>
                    <bDoShowWholeLine>true</bDoShowWholeLine>
                    <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
                </ViewSetting>
                <ShowViewSelection>
                    <Show>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Show>
                    <Keep>
                        <LineNbrPreviousToMatch>0</LineNbrPreviousToMatch>
                        <LineNbrFollowingMatch>0</LineNbrFollowingMatch>
                    </Keep>
                    <bDoShowTitle>true</bDoShowTitle>
                    <bDoShowLineNumbers>true</bDoShowLineNumbers>
                    <bDoShowFixedFont>true</bDoShowFixedFont>
                    <bDoShowFileNames>true</bDoShowFileNames>
                    <bDoShowFileContents>true</bDoShowFileContents>
                    <bDoShowWholeLine>true</bDoShowWholeLine>
                    <bDoShowDoubleBlanks>false</bDoShowDoubleBlanks>
                </ShowViewSelection>
                <SearchString>-&gt;select</SearchString>
                <ReplaceString>-&gt;loadColumn</ReplaceString>
                <SearchFileTypes>
                    <string>*.php</string>
                </SearchFileTypes>
                <SearchFileTypesAsString>*.php</SearchFileTypesAsString>
                <SearchFolders>
                    <string>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2</string>
                </SearchFolders>
                <SearchFoldersAsString>d:\xampp\htdocs\Joomla3x\administrator\components\com_rsg2</SearchFoldersAsString>
                <bWholeWordsOnly>false</bWholeWordsOnly>
                <bMatchCase>false</bMatchCase>
                <bLinesWithNoMatch>false</bLinesWithNoMatch>
                <bStopAfterFirstMatch>false</bStopAfterFirstMatch>
                <bUseRegularExpression>false</bUseRegularExpression>
                <bFilesWithNoMatch>false</bFilesWithNoMatch>
                <bSearchInFoundFiles>false</bSearchInFoundFiles>
                <bUseDelimitedList>false</bUseDelimitedList>
                <bUseFixedWidthList>false</bUseFixedWidthList>
                <bNeedsCompleteLine>false</bNeedsCompleteLine>
                <DelimitedSeperationChar />
                <DelimitedSearchFieldNbr />
                <FixedWidthBeginPosition />
                <FixedWidthSize />
                <bReplaceInSelectedFiles>false</bReplaceInSelectedFiles>
                <bConfirmEachReplace>false</bConfirmEachReplace>
                <bCreateBackup>false</bCreateBackup>
                <bReplaceOriginalFile>true</bReplaceOriginalFile>
                <bUseBackupFolder>false</bUseBackupFolder>
                <BackupFolder>Use backup folder</BackupFolder>
            </SearchProperties>
            <TokenMatchedNbr>31</TokenMatchedNbr>
            <FilesMatchedNbr>17</FilesMatchedNbr>
            <FileSearchedNbr>70</FileSearchedNbr>
            <FilesSkippedNbr>0</FilesSkippedNbr>
        </SearchResultInfo>
    </SearchResults>
</clsResultsOfOneSearch>